# HW_L03_01_numpy_pandas

This project is divided into **six sections**:

1. **Data Structure Fundamentals – NumPy Basics**
2. **Numerical Operations and Data Preprocessing**  
3. **Data Filtering and Feature Engineering**  
4. **Exploratory Data Analysis (EDA) on an ML Class Dataset**  
5. **Data Cleaning and Preprocessing**  
6. **Feature Engineering and Group Analysis**   





In [1]:
import os
import numpy as np
import pandas as pd

### 1. **Data Structure Fundamentals – NumPy Basics**



Task 1   
Create a **one-dimensional NumPy array** that contains **12 consecutive integers greater than 5**.

In [14]:
# by numpy arange
NUMBER = 5
feature_vector = np.arange(NUMBER, NUMBER + 12)
feature_vector

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [13]:
# by list and numpy array
NUMBER = 5
feature_vector = np.array([i + NUMBER for i in range(12)])
feature_vector

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

Task 2   
Create a **2D NumPy array** with shape **3×4** filled with **pseudo‑random integers between 0 and 9**.  
Use:
```python
np.random.seed(42)


In [39]:
np.random.seed(42)
feature_matrix = np.random.randint(0, 10, size=(3, 4))
feature_matrix

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]], dtype=int32)

In [45]:
print(f"feature_vector size: {feature_vector.size}, feature_matrix size: {feature_matrix.size}")
print(f"feature_vector ndim: {feature_vector.ndim}, feature_matrix ndim: {feature_matrix.ndim}")
print(f"feature_vector shape: {feature_vector.shape}, feature_matrix shape: {feature_matrix.shape}")
print(f"feature_vector dtype: {feature_vector.dtype}, feature_matrix dtype: {feature_matrix.dtype}")

feature_vector size: 12, feature_matrix size: 12
feature_vector ndim: 1, feature_matrix ndim: 2
feature_vector shape: (12,), feature_matrix shape: (3, 4)
feature_vector dtype: int64, feature_matrix dtype: int32


In [47]:
# by dataframe and table
info_feature_vector = [feature_vector.size, feature_vector.ndim, feature_vector.shape, feature_vector.dtype]
info_feature_matrix = [feature_matrix.size, feature_matrix.ndim, feature_matrix.shape, feature_matrix.dtype]

pd.DataFrame([info_feature_vector, info_feature_matrix],
             columns=["size", "ndim", "shape", "dtype"],
             index = ["feature_vector", "feature_matrix"])

,size,ndim,shape,dtype
feature_vector,12,1,"(12,)",int64
feature_matrix,12,2,"(3, 4)",int32


Task 3    
Indexing and Slicing – Accessing Data

Perform the following operations on `feature_matrix`:

- Print the element at **row 2, column 3**.
- Print the **entire first row** of `feature_matrix`.
- Print the **entire last column** of `feature_matrix`.
- Select a **2×2 submatrix from the top-right corner** of `feature_matrix`.


In [51]:
feature_matrix

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]], dtype=int32)

In [75]:
# value 2,3 = [2-1, 3-1]
print(f"row 2 and column 3 is {feature_matrix[1, 2]}")
print("---------------------------")
# row 1 = [0, :]
print(f"row 1 is {feature_matrix[0, :]}")
print("---------------------------")
# column end = [:, -1]
print(f"column end is {feature_matrix[:, -1]}")
print("---------------------------")
# Matrix 2x2 = [:2, :2] or [0:2, 0:2]
print(f"Matrix 2x2 is\n {feature_matrix[:2, :2]}") # \n print to next line

row 2 and column 3 is 2
---------------------------
row 1 is [6 3 7 4]
---------------------------
column end is [4 6 7]
---------------------------
Matrix 2x2 is
 [[6 3]
 [6 9]]


Task 4   
Reshaping Data  

* Reshape `feature_vector` into a **2D array with 4 rows and 3 columns**.

* Convert `feature_matrix` into a **1D array (flatten it)**.

In [80]:
feature_vector

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [78]:
# feature_vector is 1d -> reshape(4,3)
feature_vector.reshape(4,3)

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

In [92]:
feature_matrix

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]], dtype=int32)

In [94]:
# fisrt way -> 1d and flatten
# shape is (1, feature_vector.size)
feature_vector.reshape(1, feature_vector.size)[0]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [96]:
# second way -> 1d and flatten
feature_vector.flatten()

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

Task 5   

Combining Datasets

- Create a new **3×4 matrix** filled with ones.
- Vertically stack this matrix with your original `feature_matrix`.
- Create a **3×1 column vector** with values `[10, 20, 30]`.
- Horizontally stack this column vector to your `feature_matrix`.


In [117]:
# Create one matrix 3x4 by 1
New_Matrix_Ones = np.ones((3,4), dtype="int")
New_Matrix_Ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [118]:
# first way
# concat New_Matrix_Ones and feature_matrix by axis = 0 (vertically)
np.concatenate([New_Matrix_Ones, feature_matrix], axis= 0)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]])

In [119]:
# second way
np.vstack([New_Matrix_Ones, feature_matrix])

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]])

In [120]:
# Create one array 3x1
new_array = np.array([10, 20, 30]).reshape(3,1)
new_array

array([[10],
       [20],
       [30]])

In [123]:
# first way
# concat new_array and feature_matrix by axis = 1 (horizontally)
np.concatenate([new_array, feature_matrix], axis= 1)

array([[10,  6,  3,  7,  4],
       [20,  6,  9,  2,  6],
       [30,  7,  4,  3,  7]])

In [125]:
# second way
np.hstack([new_array, feature_matrix])


array([[10,  6,  3,  7,  4],
       [20,  6,  9,  2,  6],
       [30,  7,  4,  3,  7]])

### 2. **Numerical Operations and Data Preprocessing**  
This exercise introduces the power of **vectorized operations, aggregate functions, and broadcasting**.  
These are fundamental concepts for data preprocessing and machine learning, such as **normalization**.



Task 1   
Create a **2D NumPy array** named `scores` with shape **(15, 3)** containing **pseudo‑random integers between 50 and 100**.  
Use:

`np.random.seed(100)`

- Compute the **mean score of each test** (mean of each column).
- Compute the **standard deviation of the test scores**.
- Find the **highest score obtained in the third test**.
- Compute the **average score of each student** (mean of each row).


In [130]:
np.random.seed(100)
scores = np.random.randint(50, 101, size=(15, 3)) # [50, 101)
scores

array([[58, 74, 53],
       [89, 73, 65],
       [98, 60, 80],
       [84, 52, 84],
       [64, 84, 99],
       [98, 74, 65],
       [86, 93, 66],
       [59, 79, 72],
       [52, 77, 94],
       [54, 81, 51],
       [63, 69, 86],
       [54, 77, 53],
       [57, 99, 97],
       [51, 64, 57],
       [66, 52, 91]], dtype=int32)

In [ ]:
# Compute the mean score of each test (mean of each column)
# first way
print(f"avrage scores each test 1 : {scores[:, 0].mean():.4f}") # print folat by format .4f
print(f"avrage scores each test 2 : {scores[:, 1].mean():.4f}")
print(f"avrage scores each test 3 : {scores[:, 2].mean():.4f}")


avrage scores each test 1 : 68.8667
avrage scores each test 2 : 73.8667
avrage scores each test 3 : 74.2000


In [146]:
type(scores.shape)

tuple

In [148]:
# Second way
print(f"type of scores.shape is {type(scores.shape)}") #is one tupel by 2 value
NUMBER_TEST = scores.shape[1] # need second value
for test in range(NUMBER_TEST):
    print(f"avrage scores each test {test + 1} : {scores[:, test].mean():.4f}") 

type of scores.shape is <class 'tuple'>
avrage scores each test 1 : 68.8667
avrage scores each test 2 : 73.8667
avrage scores each test 3 : 74.2000


In [150]:
# Compute the standard deviation of the test scores
# first way
print(f"std scores each test 1 : {scores[:, 0].std():.4f}") # print folat by format .4f
print(f"std scores each test 2 : {scores[:, 1].std():.4f}")
print(f"std scores each test 3 : {scores[:, 2].std():.4f}")

std scores each test 1 : 16.5202
std scores each test 2 : 12.8264
std scores each test 3 : 16.4365


In [151]:
# Second way
print(f"type of scores.shape is {type(scores.shape)}") #is one tupel by 2 value
NUMBER_TEST = scores.shape[1] # need second value
for test in range(NUMBER_TEST):
    print(f"std scores each test {test + 1} : {scores[:, test].std():.4f}") 

type of scores.shape is <class 'tuple'>
std scores each test 1 : 16.5202
std scores each test 2 : 12.8264
std scores each test 3 : 16.4365


In [157]:
# Find the highest score obtained in the third test
# first way
print(f"Max scores 3rd test: {scores[:, 2].max()}")
# second way
print(f"Max scores 3rd test: {scores[:, -1].max()}")


Max scores 3rd test: 99
Max scores 3rd test: 99


In [198]:
# Compute the average score of each student(mean of each row)
# first way
print(f"avrage scores each student: \n{scores.mean(axis=1)}")

avrage scores each student: 
[61.66666667 75.66666667 79.33333333 73.33333333 82.33333333 79.
 81.66666667 70.         74.33333333 62.         72.66666667 61.33333333
 84.33333333 57.33333333 69.66666667]


In [199]:
# first way
TOTAL_ROW = scores.shape[0] # total row = scores.shape[0]
avrage_student_score = scores.mean(axis=1).reshape(TOTAL_ROW, 1)
print(f"avrage scores each student: \n{avrage_student_score}")


avrage scores each student: 
[[61.66666667]
 [75.66666667]
 [79.33333333]
 [73.33333333]
 [82.33333333]
 [79.        ]
 [81.66666667]
 [70.        ]
 [74.33333333]
 [62.        ]
 [72.66666667]
 [61.33333333]
 [84.33333333]
 [57.33333333]
 [69.66666667]]


Task 2   
Broadcasting

Assume the instructor decides to improve all students' scores in the **first test** by adding **5 points**.

Create a new array called `curved_scores` in which **only the first column** of the `scores` array has increased by **5**.

Use **broadcasting** to do this.


In [234]:
print(f"main score test 1 \n{scores[:,0]}")
print("---------------------first way----------------------")
# first way
curved_scores = np.array(scores[:,0] + 5)
print(f"test number 1 add 5 score to esch score \n{curved_scores}")
print("---------------------second way--------------------")
# second way
curved_scores = np.add(scores[:, 0], 5)
print(f"test number 1 add 5 score to esch score \n{curved_scores}")

main score test 1 
[58 89 98 84 64 98 86 59 52 54 63 54 57 51 66]
---------------------first way----------------------
test number 1 add 5 score to esch score 
[ 63  94 103  89  69 103  91  64  57  59  68  59  62  56  71]
---------------------second way--------------------
test number 1 add 5 score to esch score 
[ 63  94 103  89  69 103  91  64  57  59  68  59  62  56  71]


In [232]:
print("time run each way")
%timeit np.array(scores[:,0] + 5)
%timeit np.add(scores[:, 0], 5)

time run each way
39.6 μs ± 17 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
22.1 μs ± 5.12 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


Task 3    
Data Normalization

A very common step in ML data preprocessing is **feature normalization**. This is achieved by subtracting the mean and dividing by the standard deviation for each feature.

- Calculate the **mean** and **standard deviation** of each test from the original `scores` array.
- Create a new array named `normalized_scores` using the **Z-score** formula:
  
  $$(scores - mean) / std$$

  You must correctly apply **broadcasting** to subtract the 1D `mean` and `std` arrays from the 2D `scores` matrix and then divide.
- To verify your results, calculate the mean and standard deviation for each column of `normalized_scores`. The mean should be very close to **0**, and the standard deviation should be very close to **1**.


In [274]:
# Calculate the mean and std of each test

NUMBER_COLUMN = scores.shape[1]

for test in range(NUMBER_COLUMN):
    print(f"test number {test +1}: mean: {scores[:,test].mean():.4f} -- std: {scores[:,test].std():.4f}")

test number 1: mean: 68.8667 -- std: 16.5202
test number 2: mean: 73.8667 -- std: 12.8264
test number 3: mean: 74.2000 -- std: 16.4365


In [276]:
# Create a new array named normalized_scores using the Z-score
# first way
normalized_scores = (scores - (scores.mean(axis=0))) / (scores.std(axis=0))
print(normalized_scores)


[[-0.65778233  0.01039526 -1.2898088 ]
 [ 1.21871327 -0.06756917 -0.55972835]
 [ 1.76350231 -1.08110678  0.35287222]
 [ 0.91605269 -1.70482223  0.59623237]
 [-0.29458963  0.79003957  1.50883294]
 [ 1.76350231  0.01039526 -0.55972835]
 [ 1.03711692  1.49171945 -0.49888831]
 [-0.59725021  0.40021741 -0.13384808]
 [-1.02097502  0.24428855  1.20463275]
 [-0.89991079  0.55614628 -1.41148888]
 [-0.35512175 -0.3794269   0.71791245]
 [-0.89991079  0.24428855 -1.2898088 ]
 [-0.71831444  1.95950604  1.38715286]
 [-1.08150714 -0.76924906 -1.04644865]
 [-0.1735254  -1.70482223  1.02211264]]


In [277]:
# second way
STD_COLUMN = scores.std(axis=0) # in column
STD_MEAN = scores.mean(axis=0) # in column
normalized_scores = (scores - STD_MEAN) / STD_COLUMN
normalized_scores

array([[-0.65778233,  0.01039526, -1.2898088 ],
       [ 1.21871327, -0.06756917, -0.55972835],
       [ 1.76350231, -1.08110678,  0.35287222],
       [ 0.91605269, -1.70482223,  0.59623237],
       [-0.29458963,  0.79003957,  1.50883294],
       [ 1.76350231,  0.01039526, -0.55972835],
       [ 1.03711692,  1.49171945, -0.49888831],
       [-0.59725021,  0.40021741, -0.13384808],
       [-1.02097502,  0.24428855,  1.20463275],
       [-0.89991079,  0.55614628, -1.41148888],
       [-0.35512175, -0.3794269 ,  0.71791245],
       [-0.89991079,  0.24428855, -1.2898088 ],
       [-0.71831444,  1.95950604,  1.38715286],
       [-1.08150714, -0.76924906, -1.04644865],
       [-0.1735254 , -1.70482223,  1.02211264]])

In [278]:
# Third way
STD_COLUMN = scores.std(axis=0) # in column
STD_MEAN = scores.mean(axis=0) # in column
normalized_scores = np.divide(np.subtract(scores, STD_MEAN), STD_COLUMN)
normalized_scores

array([[-0.65778233,  0.01039526, -1.2898088 ],
       [ 1.21871327, -0.06756917, -0.55972835],
       [ 1.76350231, -1.08110678,  0.35287222],
       [ 0.91605269, -1.70482223,  0.59623237],
       [-0.29458963,  0.79003957,  1.50883294],
       [ 1.76350231,  0.01039526, -0.55972835],
       [ 1.03711692,  1.49171945, -0.49888831],
       [-0.59725021,  0.40021741, -0.13384808],
       [-1.02097502,  0.24428855,  1.20463275],
       [-0.89991079,  0.55614628, -1.41148888],
       [-0.35512175, -0.3794269 ,  0.71791245],
       [-0.89991079,  0.24428855, -1.2898088 ],
       [-0.71831444,  1.95950604,  1.38715286],
       [-1.08150714, -0.76924906, -1.04644865],
       [-0.1735254 , -1.70482223,  1.02211264]])

In [290]:
# test part 2 if std is 1 and mean is 0
NUMER_COLUMN_NORMALIZED = normalized_scores.shape[1]
print("std and mean nomalized score each test is by format .10f:")
for i in range(NUMER_COLUMN_NORMALIZED):
    print(f"Normalized score test number {i +1}: mean: {normalized_scores[:,i].mean():.10f} -- std: {normalized_scores[:,i].std():.10f}")
    

std and mean nomalized score each test is by format .10f:
Normalized score test number 1: mean: 0.0000000000 -- std: 1.0000000000
Normalized score test number 2: mean: 0.0000000000 -- std: 1.0000000000
Normalized score test number 3: mean: -0.0000000000 -- std: 1.0000000000


### 3. Data Filtering and Feature Engineering

**Objective:** This exercise focuses on using **Boolean masking** to filter data and create new features.

In this exercise, we will continue to use the same `scores` dataset from the previous exercise.


Task 1   
Identifying Top Students

- Create a **Boolean mask** that identifies all scores in the `scores` array that are **greater than 95**.
- Using this mask, **count the number of scores above 95**.
- Create a new array called `high_performers_scores` that contains **only the scores

In [300]:
scores

array([[58, 74, 53],
       [89, 73, 65],
       [98, 60, 80],
       [84, 52, 84],
       [64, 84, 99],
       [98, 74, 65],
       [86, 93, 66],
       [59, 79, 72],
       [52, 77, 94],
       [54, 81, 51],
       [63, 69, 86],
       [54, 77, 53],
       [57, 99, 97],
       [51, 64, 57],
       [66, 52, 91]], dtype=int32)

In [ ]:
# Create a Boolean mask that identifies all scores in the scores array that are greater than 95

# MASK_SCORE_GREATER_95 = scores > 95
MASK_SCORE_GREATER_95 = np.greater_equal(scores, 95)
MASK_SCORE_GREATER_95

array([[False, False, False],
       [False, False, False],
       [ True, False, False],
       [False, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True,  True],
       [False, False, False],
       [False, False, False]])

In [ ]:
# Using this mask, count the number of scores above 95
print(f"total scores greater equal than 95 is {MASK_SCORE_GREATER_95.sum()}")


np.int64(5)