# HW_L03_01_numpy_pandas

This project is divided into **six sections**:

1. **Data Structure Fundamentals – NumPy Basics**
2. **Numerical Operations and Data Preprocessing**  
3. **Data Filtering and Feature Engineering**  
4. **Exploratory Data Analysis (EDA) on an ML Class Dataset**  
5. **Data Cleaning and Preprocessing**  
6. **Feature Engineering and Group Analysis**   





In [1]:
import os
import numpy as np
import pandas as pd

### 1. **Data Structure Fundamentals – NumPy Basics**



Task 1   
Create a **one-dimensional NumPy array** that contains **12 consecutive integers greater than 5**.

In [14]:
# by numpy arange
NUMBER = 5
feature_vector = np.arange(NUMBER, NUMBER + 12)
feature_vector

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [13]:
# by list and numpy array
NUMBER = 5
feature_vector = np.array([i + NUMBER for i in range(12)])
feature_vector

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

Task 2   
Create a **2D NumPy array** with shape **3×4** filled with **pseudo‑random integers between 0 and 9**.  
Use:
```python
np.random.seed(42)


In [39]:
np.random.seed(42)
feature_matrix = np.random.randint(0, 10, size=(3, 4))
feature_matrix

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]], dtype=int32)

In [45]:
print(f"feature_vector size: {feature_vector.size}, feature_matrix size: {feature_matrix.size}")
print(f"feature_vector ndim: {feature_vector.ndim}, feature_matrix ndim: {feature_matrix.ndim}")
print(f"feature_vector shape: {feature_vector.shape}, feature_matrix shape: {feature_matrix.shape}")
print(f"feature_vector dtype: {feature_vector.dtype}, feature_matrix dtype: {feature_matrix.dtype}")

feature_vector size: 12, feature_matrix size: 12
feature_vector ndim: 1, feature_matrix ndim: 2
feature_vector shape: (12,), feature_matrix shape: (3, 4)
feature_vector dtype: int64, feature_matrix dtype: int32


In [47]:
# by dataframe and table
info_feature_vector = [feature_vector.size, feature_vector.ndim, feature_vector.shape, feature_vector.dtype]
info_feature_matrix = [feature_matrix.size, feature_matrix.ndim, feature_matrix.shape, feature_matrix.dtype]

pd.DataFrame([info_feature_vector, info_feature_matrix],
             columns=["size", "ndim", "shape", "dtype"],
             index = ["feature_vector", "feature_matrix"])

,size,ndim,shape,dtype
feature_vector,12,1,"(12,)",int64
feature_matrix,12,2,"(3, 4)",int32


Task 3    
Indexing and Slicing – Accessing Data

Perform the following operations on `feature_matrix`:

- Print the element at **row 2, column 3**.
- Print the **entire first row** of `feature_matrix`.
- Print the **entire last column** of `feature_matrix`.
- Select a **2×2 submatrix from the top-right corner** of `feature_matrix`.


In [51]:
feature_matrix

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]], dtype=int32)

In [75]:
# value 2,3 = [2-1, 3-1]
print(f"row 2 and column 3 is {feature_matrix[1, 2]}")
print("---------------------------")
# row 1 = [0, :]
print(f"row 1 is {feature_matrix[0, :]}")
print("---------------------------")
# column end = [:, -1]
print(f"column end is {feature_matrix[:, -1]}")
print("---------------------------")
# Matrix 2x2 = [:2, :2] or [0:2, 0:2]
print(f"Matrix 2x2 is\n {feature_matrix[:2, :2]}") # \n print to next line

row 2 and column 3 is 2
---------------------------
row 1 is [6 3 7 4]
---------------------------
column end is [4 6 7]
---------------------------
Matrix 2x2 is
 [[6 3]
 [6 9]]


Task 4   
Reshaping Data  

* Reshape `feature_vector` into a **2D array with 4 rows and 3 columns**.

* Convert `feature_matrix` into a **1D array (flatten it)**.

In [80]:
feature_vector

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [78]:
# feature_vector is 1d -> reshape(4,3)
feature_vector.reshape(4,3)

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

In [92]:
feature_matrix

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]], dtype=int32)

In [94]:
# fisrt way -> 1d and flatten
# shape is (1, feature_vector.size)
feature_vector.reshape(1, feature_vector.size)[0]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [96]:
# second way -> 1d and flatten
feature_vector.flatten()

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])