# Linear Algebra

We use `numpy` for Linear Algebra

In [1]:
import numpy as np

## Vector

create one Vector

In [2]:
a = np.array([25, 10000, 5])
print(f"Vector : {a}")
print(f"wight of Vector: {len(a)}")


Vector : [   25 10000     5]
wight of Vector: 3


In [3]:
# student
parsa = np.array([19, 20, 18, 16, 17, 18])
arad = np.array([18,19,16,20,15,17])

In [4]:
print(f"parsa : {parsa}")
print(f"arad : {arad}")

parsa : [19 20 18 16 17 18]
arad : [18 19 16 20 15 17]


In [5]:
hasan = np.array([14.5 , 15, 16.75 , 20 , 17.25 , 18])
print(hasan)

[14.5  15.   16.75 20.   17.25 18.  ]


In [6]:
a = np.array([1 , 2])
b = np.array([1 , 2])
c = np.array([1 , 2])
print(a)
print(b)
print(c)

[1 2]
[1 2]
[1 2]


In [7]:
d = e = f = np.array([3,4])
print(d)
print(e)
print(f)

[3 4]
[3 4]
[3 4]


In [8]:
# create 3 Vector in in one line, each Vector has one unique value
g , h , i = np.array([5 ,6]) , np.array ([1 ,2]) , np.array([5 , 6])

In [9]:
print(g)
print(h)
print(i)

[5 6]
[1 2]
[5 6]


In [10]:
a = np.array([0 , 1 ,2 ,3 ,4])
print(a)

a = np.arange(5)
print(a)

a = np.arange(2, 5)
print(a)

a = np.arange(10, 1, -1) # step = -1
print(a)

a = np.arange(2, 22, 2) # step = 2
print(a)

# other way
a = np.arange(1, 11)*2 # step = 2
print(a)

[0 1 2 3 4]
[0 1 2 3 4]
[2 3 4]
[10  9  8  7  6  5  4  3  2]
[ 2  4  6  8 10 12 14 16 18 20]
[ 2  4  6  8 10 12 14 16 18 20]


In [11]:
a = np.array([1,5,0,12,2,23,4])
print(a)

# indexing
print(a[0])
print(a[2])
print(a[-1])

[ 1  5  0 12  2 23  4]
1
0
4


Zoros and ones Vector

In [12]:
a = np.zeros(3)
print(a)
print("--------")

a = np.zeros(7)
print(a)
print("--------")

a = np.ones(3)
print(a)
print("--------")

a = np.ones(9)
print(a)
print("--------")

a = np.ones((2,3))
print(a)

[0. 0. 0.]
--------
[0. 0. 0. 0. 0. 0. 0.]
--------
[1. 1. 1.]
--------
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
--------
[[1. 1. 1.]
 [1. 1. 1.]]


## Opetarors in Vectors

Addition and subtraction

In [13]:
s = np.array([20 , 15])
m = np.array([25 , 10])

print(f"s =     {s}")
print(f"m =     {m}")

t_p = s + m
print(f"s + m = {t_p}")

t_p = np.add(s, m)
print(f"s + m = {t_p}")

t_p = np.sum([s, m], axis=0)
print(f"s + m = {t_p}")


t_n = s - m
print(f"s - m = {t_n}")

t_p = np.subtract(s, m)
print(f"s - m = {t_p}")



s =     [20 15]
m =     [25 10]
s + m = [45 25]
s + m = [45 25]
s + m = [45 25]
s - m = [-5  5]
s - m = [-5  5]


power

In [14]:
a = np.array ([12 , 10])
print(a)

print(a*3)

[12 10]
[36 30]


dot product

In [15]:
a = np.array([2 , 4])
b = np.array([4 , 10])

print(a)
print(b)

print(np.dot(a , b))

[2 4]
[ 4 10]
48


In [16]:
a = np.array([3 , -4 , 5])
b = np.array([-1 , 1/2 , 10])

print(a)
print(b)

print(np.dot(a , b))

[ 3 -4  5]
[-1.   0.5 10. ]
45.0


## Matrices

In [17]:
# create one Matrix
M=np.array([[20,12],
            [25,15],
            [23,13]])
print(M)

[[20 12]
 [25 15]
 [23 13]]


In [18]:
# Matrix size
print(np.shape(M))

(3, 2)


In [19]:
M=np.array([[2,6],
            [-1,5]])
print(M)

print(np.shape(M))

[[ 2  6]
 [-1  5]]
(2, 2)


In [20]:
# diagonal
t=np.diag(M)
print(t)

[2 5]


In [21]:
# Matrix in numpy
A=np.asmatrix([[1,0,5],
          [-2,6,7],
          [3,10,15]])
print(A)

[[ 1  0  5]
 [-2  6  7]
 [ 3 10 15]]


In [22]:
t=np.diag(A)
print(t)

[ 1  6 15]


In [23]:
B=np.array([[4,6,7],
           [10,-4,7],
           [11,14,15]])
print(B)

[[ 4  6  7]
 [10 -4  7]
 [11 14 15]]


In [24]:
print(B[0,0])

4


In [25]:
print(B[1,2])

7


In [26]:
B[1,0]=30
print(B)

[[ 4  6  7]
 [30 -4  7]
 [11 14 15]]


In [27]:
C=np.array([[10,20],
            [30,40],
            [50,60]])
print(C)

[[10 20]
 [30 40]
 [50 60]]


In [29]:
# transpose
print(C.T)

[[10 30 50]
 [20 40 60]]


In [30]:
print(C.T.T)


[[10 20]
 [30 40]
 [50 60]]


In [31]:
A=np.asmatrix([[1,5,6],
               [5,8,7],
               [6,7,10]])
print(A)
B=A.T

print(A==B)

[[ 1  5  6]
 [ 5  8  7]
 [ 6  7 10]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [32]:
A=np.asmatrix([[1,5,7],
               [5,8,7],
               [6,11,10]])
print(A)
B=A.T

print(A==B)

[[ 1  5  7]
 [ 5  8  7]
 [ 6 11 10]]
[[ True  True False]
 [ True  True False]
 [False False  True]]


In [34]:
A=np.asmatrix([[1,5,8],
               [5,8,7]
               ])
print(A)

B=A.T
print(A==B) # Error
# ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

[[1 5 8]
 [5 8 7]]


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [37]:
A=np.identity(4)
print(A)
print("--------------")
A=np.eye(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
--------------
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [39]:
A = np.diagflat([1,6,5,20])
print(A)

[[ 1  0  0  0]
 [ 0  6  0  0]
 [ 0  0  5  0]
 [ 0  0  0 20]]


In [40]:
A = np.zeros((2,5))
print(A)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [41]:
A = np.ones((4,6))
print(A)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [42]:
A=np.array([[2,5,6],
            [7,-5,8]])
print(A)
print(3*A)

[[ 2  5  6]
 [ 7 -5  8]]
[[  6  15  18]
 [ 21 -15  24]]


In [43]:
B=np.array([[4,8,10],
            [5,1,0]])
print(A)
print(B)

[[ 2  5  6]
 [ 7 -5  8]]
[[ 4  8 10]
 [ 5  1  0]]


In [44]:
print(A+B)

[[ 6 13 16]
 [12 -4  8]]


In [45]:
print(A*B)

[[ 8 40 60]
 [35 -5  0]]
