# Linear Algebra

We use `numpy` for Linear Algebra

In [1]:
import numpy as np

## Vector

create one Vector

In [6]:
a = np.array([25, 10000, 5])
print(f"Vector : {a}")
print(f"wight of Vector: {len(a)}")


Vector : [   25 10000     5]
wight of Vector: 3


In [8]:
# student
parsa = np.array([19, 20, 18, 16, 17, 18])
arad = np.array([18,19,16,20,15,17])

In [9]:
print(f"parsa : {parsa}")
print(f"arad : {arad}")

parsa : [19 20 18 16 17 18]
arad : [18 19 16 20 15 17]


In [10]:
hasan = np.array([14.5 , 15, 16.75 , 20 , 17.25 , 18])
print(hasan)

[14.5  15.   16.75 20.   17.25 18.  ]


In [11]:
a = np.array([1 , 2])
b = np.array([1 , 2])
c = np.array([1 , 2])
print(a)
print(b)
print(c)

[1 2]
[1 2]
[1 2]


In [12]:
d = e = f = np.array([3,4])
print(d)
print(e)
print(f)

[3 4]
[3 4]
[3 4]


In [ ]:
# create 3 Vector in in one line, each Vector has one unique value
g , h , i = np.array([5 ,6]) , np.array ([1 ,2]) , np.array([5 , 6])

In [ ]:
print(g)
print(h)
print(i)

[5 6]
[1 2]
[5 6]


In [29]:
a = np.array([0 , 1 ,2 ,3 ,4])
print(a)

a = np.arange(5)
print(a)

a = np.arange(2, 5)
print(a)

a = np.arange(10, 1, -1) # step = -1
print(a)

a = np.arange(2, 22, 2) # step = 2
print(a)

# other way
a = np.arange(1, 11)*2 # step = 2
print(a)

[0 1 2 3 4]
[0 1 2 3 4]
[2 3 4]
[10  9  8  7  6  5  4  3  2]
[ 2  4  6  8 10 12 14 16 18 20]
[ 2  4  6  8 10 12 14 16 18 20]


In [32]:
a = np.array([1,5,0,12,2,23,4])
print(a)

# indexing
print(a[0])
print(a[2])
print(a[-1])

[ 1  5  0 12  2 23  4]
1
0
4


Zoros and ones Vector

In [39]:
a = np.zeros(3)
print(a)
print("--------")

a = np.zeros(7)
print(a)
print("--------")

a = np.ones(3)
print(a)
print("--------")

a = np.ones(9)
print(a)
print("--------")

a = np.ones((2,3))
print(a)

[0. 0. 0.]
--------
[0. 0. 0. 0. 0. 0. 0.]
--------
[1. 1. 1.]
--------
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
--------
[[1. 1. 1.]
 [1. 1. 1.]]
