# Tensor

In [1]:
import torch
import numpy as np

versio of torch

In [2]:
torch.__version__

'2.12.1+cu126'

Create one array by torch    
array in numpy = tensor in torch

In [3]:
tensor1d = torch.tensor([1, -1, 15, 1000])
print(tensor1d)

tensor([   1,   -1,   15, 1000])


In [4]:
np.array([1, -1, 15, 1000])

array([   1,   -1,   15, 1000])

In [5]:
tensor2d = torch.tensor([[-10, 11, 1.5],
                             [ 5.6, 88, 10.0],
                             [ 2.3, 36, -10.0],
                             [ 2.0, 12, 0.2]])
print(tensor2d)

tensor([[-10.0000,  11.0000,   1.5000],
        [  5.6000,  88.0000,  10.0000],
        [  2.3000,  36.0000, -10.0000],
        [  2.0000,  12.0000,   0.2000]])


In [6]:
np.array([[-10, 11, 1.5],
        [ 5.6, 88, 10.0],
        [ 2.3, 36, -10.0],
        [ 2.0, 12, 0.2]])

array([[-10. ,  11. ,   1.5],
       [  5.6,  88. ,  10. ],
       [  2.3,  36. , -10. ],
       [  2. ,  12. ,   0.2]])

In [7]:
tensor3d = torch.tensor([[[-10, 11, 1.50],
                              [ 5.6, 88, 10.0],
                              [ 2.3, 36, -10.0],
                              [ 2.0, 12, 0.2]],
                             [[-1.0, 11, 1.50],
                              [ 0.6, 88, 1.00],
                              [ 0.3, 3.6, -10.0],
                              [ 2.1, 1.2, 4.20]]])

print(tensor3d)

tensor([[[-10.0000,  11.0000,   1.5000],
         [  5.6000,  88.0000,  10.0000],
         [  2.3000,  36.0000, -10.0000],
         [  2.0000,  12.0000,   0.2000]],

        [[ -1.0000,  11.0000,   1.5000],
         [  0.6000,  88.0000,   1.0000],
         [  0.3000,   3.6000, -10.0000],
         [  2.1000,   1.2000,   4.2000]]])


In [8]:
tensor2d.shape

torch.Size([4, 3])

In [9]:
tensor2d.size()

torch.Size([4, 3])

In [10]:
tensor1d.dtype

torch.int64

Zeros in torch

In [11]:
zeros1d = torch.zeros(1)
print(zeros1d)

tensor([0.])


In [12]:
zeros1d = torch.zeros(5)
print(zeros1d)

tensor([0., 0., 0., 0., 0.])


In [13]:
zeros2d = torch.zeros(2, 3)
print(zeros2d)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [14]:
zeros5d = torch.zeros(2, 3, 8, 6, 5)
print(zeros5d.shape)
print(zeros5d)

torch.Size([2, 3, 8, 6, 5])
tensor([[[[[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          ...,

          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 

numel : number of element of one tensor

In [15]:
print(zeros5d.shape)
manual_count_element = 1
for i in (zeros5d.shape):
    manual_count_element *= i

print(f"manual count element : {manual_count_element}")



torch.Size([2, 3, 8, 6, 5])
manual count element : 1440


In [16]:
print(zeros5d.numel())

1440


change type

In [17]:
zeros2d = torch.zeros(2, 2, dtype=torch.float64)
print(zeros2d)

tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)


In [18]:
ones1d = torch.ones(4)
print(ones1d)

tensor([1., 1., 1., 1.])


In [19]:
ones2d = torch.ones(4, 8)
print(ones2d)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])


In [20]:
ones3d = torch.ones(3, 2, 4, dtype=torch.int16)
print(ones3d)

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1]]], dtype=torch.int16)


In [21]:
full2d = torch.full((3,4), 5)
print(full2d)

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])


In [22]:
eye_tensor = torch.eye(5)
print(eye_tensor)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


tensor from start to end by step step      
`torch.arange(start, end, step)`   
result:    [ start, ... , end )

In [23]:
arange_tensor = torch.arange(0, 10, 1)
print(arange_tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [24]:
arange_tensor = torch.arange(1.5, 2.5, 0.1)
print(arange_tensor)

tensor([1.5000, 1.6000, 1.7000, 1.8000, 1.9000, 2.0000, 2.1000, 2.2000, 2.3000,
        2.4000])


tensor between start and end and count of selection   
`torch.linspace(start, end, count of selection)`    
result:   [  start, ... , end  ]

In [25]:
linspace_tensor = torch.linspace(0, 1, 100)
print(linspace_tensor)

tensor([0.0000, 0.0101, 0.0202, 0.0303, 0.0404, 0.0505, 0.0606, 0.0707, 0.0808,
        0.0909, 0.1010, 0.1111, 0.1212, 0.1313, 0.1414, 0.1515, 0.1616, 0.1717,
        0.1818, 0.1919, 0.2020, 0.2121, 0.2222, 0.2323, 0.2424, 0.2525, 0.2626,
        0.2727, 0.2828, 0.2929, 0.3030, 0.3131, 0.3232, 0.3333, 0.3434, 0.3535,
        0.3636, 0.3737, 0.3838, 0.3939, 0.4040, 0.4141, 0.4242, 0.4343, 0.4444,
        0.4545, 0.4646, 0.4747, 0.4848, 0.4949, 0.5051, 0.5152, 0.5253, 0.5354,
        0.5455, 0.5556, 0.5657, 0.5758, 0.5859, 0.5960, 0.6061, 0.6162, 0.6263,
        0.6364, 0.6465, 0.6566, 0.6667, 0.6768, 0.6869, 0.6970, 0.7071, 0.7172,
        0.7273, 0.7374, 0.7475, 0.7576, 0.7677, 0.7778, 0.7879, 0.7980, 0.8081,
        0.8182, 0.8283, 0.8384, 0.8485, 0.8586, 0.8687, 0.8788, 0.8889, 0.8990,
        0.9091, 0.9192, 0.9293, 0.9394, 0.9495, 0.9596, 0.9697, 0.9798, 0.9899,
        1.0000])


In [26]:
a = torch.rand(2,2)
b = torch.rand(2,2)
print(a)
print(b)
c = a + b
print(c)

tensor([[0.7028, 0.3645],
        [0.6313, 0.6204]])
tensor([[0.2004, 0.8541],
        [0.0780, 0.5598]])
tensor([[0.9032, 1.2186],
        [0.7093, 1.1802]])


In [27]:
a = torch.rand(1, 2, 3)
print(a)
b = 2.5
c = a + b
print(c)

tensor([[[0.6492, 0.0055, 0.2879],
         [0.7225, 0.9339, 0.0942]]])
tensor([[[3.1492, 2.5055, 2.7879],
         [3.2225, 3.4339, 2.5942]]])


out=input+alpha×other

In [28]:
alpha = 0.3
c = a + alpha * b
print(c)

tensor([[[1.3992, 0.7555, 1.0379],
         [1.4725, 1.6839, 0.8442]]])


In [ ]:
# add(input, other, *, alpha=1, out=None) -> Tensor

d = torch.add(a, b, alpha=alpha)
print(d)

tensor([[[1.3992, 0.7555, 1.0379],
         [1.4725, 1.6839, 0.8442]]])


In [33]:
b1 = torch.randn(4)
c1 = torch.randn(4, 1)
print(b1)
print(c1)
print(b1 + c1 * 10)
print(torch.add(b1, c1, alpha=10))

tensor([ 0.1525, -1.8331, -1.1451,  0.0218])
tensor([[-0.1750],
        [-1.0553],
        [-0.1571],
        [ 1.0205]])
tensor([[ -1.5972,  -3.5828,  -2.8948,  -1.7279],
        [-10.4004, -12.3860, -11.6980, -10.5311],
        [ -1.4185,  -3.4041,  -2.7161,  -1.5492],
        [ 10.3571,   8.3716,   9.0595,  10.2265]])
tensor([[ -1.5972,  -3.5828,  -2.8948,  -1.7279],
        [-10.4004, -12.3860, -11.6980, -10.5311],
        [ -1.4185,  -3.4041,  -2.7161,  -1.5492],
        [ 10.3571,   8.3716,   9.0595,  10.2265]])


In [34]:
a = torch.randint(10, (4,2))
print(a)
b = torch.randint(10, (2,))
print(b)
c = a * b
print(c)

tensor([[0, 2],
        [4, 7],
        [6, 8],
        [6, 4]])
tensor([3, 8])
tensor([[ 0, 16],
        [12, 56],
        [18, 64],
        [18, 32]])


In [36]:
a = torch.randn(4,2)
b = torch.randn(2,4)
print(a)
print("---------------")
print(b)
print("---------------")

c = torch.matmul(a, b)
print(c)

tensor([[ 0.3177,  0.7980],
        [-0.5629, -1.0090],
        [-0.1729,  0.2710],
        [-0.5690,  0.4861]])
---------------
tensor([[-0.4250,  1.1122, -0.0373, -0.2712],
        [-0.6156,  1.9288, -0.4574,  0.8616]])
---------------
tensor([[-0.6262,  1.8926, -0.3769,  0.6014],
        [ 0.8603, -2.5722,  0.4826, -0.7167],
        [-0.0934,  0.3305, -0.1175,  0.2804],
        [-0.0574,  0.3049, -0.2012,  0.5732]])


In [37]:
c = a @ b
print(c)

tensor([[-0.6262,  1.8926, -0.3769,  0.6014],
        [ 0.8603, -2.5722,  0.4826, -0.7167],
        [-0.0934,  0.3305, -0.1175,  0.2804],
        [-0.0574,  0.3049, -0.2012,  0.5732]])
