# Tensor

In [1]:
import torch
import numpy as np

versio of torch

In [ ]:
torch.__version__

'2.12.1+cu126'

Create one array by torch    
array in numpy = tensor in torch

In [3]:
tensor1d = torch.tensor([1, -1, 15, 1000])
print(tensor1d)

tensor([   1,   -1,   15, 1000])


In [4]:
np.array([1, -1, 15, 1000])

array([   1,   -1,   15, 1000])

In [5]:
tensor2d = torch.tensor([[-10, 11, 1.5],
                             [ 5.6, 88, 10.0],
                             [ 2.3, 36, -10.0],
                             [ 2.0, 12, 0.2]])
print(tensor2d)

tensor([[-10.0000,  11.0000,   1.5000],
        [  5.6000,  88.0000,  10.0000],
        [  2.3000,  36.0000, -10.0000],
        [  2.0000,  12.0000,   0.2000]])


In [6]:
np.array([[-10, 11, 1.5],
        [ 5.6, 88, 10.0],
        [ 2.3, 36, -10.0],
        [ 2.0, 12, 0.2]])

array([[-10. ,  11. ,   1.5],
       [  5.6,  88. ,  10. ],
       [  2.3,  36. , -10. ],
       [  2. ,  12. ,   0.2]])

In [7]:
tensor3d = torch.tensor([[[-10, 11, 1.50],
                              [ 5.6, 88, 10.0],
                              [ 2.3, 36, -10.0],
                              [ 2.0, 12, 0.2]],
                             [[-1.0, 11, 1.50],
                              [ 0.6, 88, 1.00],
                              [ 0.3, 3.6, -10.0],
                              [ 2.1, 1.2, 4.20]]])

print(tensor3d)

tensor([[[-10.0000,  11.0000,   1.5000],
         [  5.6000,  88.0000,  10.0000],
         [  2.3000,  36.0000, -10.0000],
         [  2.0000,  12.0000,   0.2000]],

        [[ -1.0000,  11.0000,   1.5000],
         [  0.6000,  88.0000,   1.0000],
         [  0.3000,   3.6000, -10.0000],
         [  2.1000,   1.2000,   4.2000]]])


In [8]:
tensor2d.shape

torch.Size([4, 3])

In [9]:
tensor2d.size()

torch.Size([4, 3])

In [10]:
tensor1d.dtype

torch.int64

Zeros in torch

In [11]:
zeros1d = torch.zeros(1)
print(zeros1d)

tensor([0.])


In [12]:
zeros1d = torch.zeros(5)
print(zeros1d)

tensor([0., 0., 0., 0., 0.])


In [13]:
zeros2d = torch.zeros(2, 3)
print(zeros2d)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [15]:
zeros5d = torch.zeros(2, 3, 8, 6, 5)
print(zeros5d.shape)
print(zeros5d)

torch.Size([2, 3, 8, 6, 5])
tensor([[[[[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          ...,

          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.]],

          [[0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0.],
           [0., 0., 0., 

numel : number of element of one tensor

In [31]:
print(zeros5d.shape)
manual_count_element = 1
for i in (zeros5d.shape):
    manual_count_element *= i

print(f"manual count element : {manual_count_element}")



torch.Size([2, 3, 8, 6, 5])
manual count element : 1440


In [17]:
print(zeros5d.numel())

1440


change type

In [32]:
zeros2d = torch.zeros(2, 2, dtype=torch.float64)
print(zeros2d)

tensor([[0., 0.],
        [0., 0.]], dtype=torch.float64)


In [33]:
ones1d = torch.ones(4)
print(ones1d)

tensor([1., 1., 1., 1.])


In [34]:
ones2d = torch.ones(4, 8)
print(ones2d)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])


In [44]:
ones3d = torch.ones(3, 2, 4, dtype=torch.int16)
print(ones3d)

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1]]], dtype=torch.int16)


In [45]:
full2d = torch.full((3,4), 5)
print(full2d)

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])


In [46]:
eye_tensor = torch.eye(5)
print(eye_tensor)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
