# Numpy

NumPy (Numerical Python) is one of the most important Python libraries for performing numerical computations and working with arrays and multidimensional matrices. The core of this library is a data structure called ndarray, which enables fast storage and processing of numerical data. NumPy performs many mathematical, statistical, and matrix operations efficiently and with high speed (because it is implemented in the C language), and for this reason it is considered the foundation of many scientific and data‑oriented Python libraries.

Applications of NumPy:

* Processing and analyzing numerical data  
* Performing matrix operations and linear algebra  
* Use in Data Science  
* Implementing and training Machine Learning models  
* Image and signal processing  
* Performing simulations and scientific computations  
* The foundation for libraries such as Pandas, SciPy, TensorFlow, and PyTorch

-----

`pip install numpy`   
`import numpy as np`


In [8]:
import numpy
numpy.__version__

'2.4.2'

In [ ]:
pip install numpy

# or
# !pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [9]:
np?

Type:        module
String form: <module 'numpy' from 'c:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python314\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\hp\appdata\local\programs\python\python314\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are i

## Data type

In [4]:
print(f"str     : 'Mohsen'  {type("Mohsen")}")
print(f"int     : 10  {type(10)}")
print(f"float   : 10.1258  {type(10.1258)}")
print(f"float   : 3.5e4  {type(3.5e4)}")
print(f"bool    : True or False  {type(True)}")
print(f"complex : 3 + 4j  {type(3 + 4j)}")
print(f"list    : [1, 2, 'mohsen']  {type([1, 2, 'mohsen'])}")
print(f"tuple   : (1, 2, 'mohsen')  {type((1, 2, 'mohsen'))}")
print(f"set     :  {{1, 2, 2, 3, 1, 4}}  {type({1, 2, 2, 3, 1, 4})} and result {set([1, 2, 2, 3, 1, 4])}")
print(f"dict    : {{'name': 'Mohsen', 'age':33}}  {type({'name': 'Mohsen', 'age':33})}")




str     : 'Mohsen'  <class 'str'>
int     : 10  <class 'int'>
float   : 10.1258  <class 'float'>
float   : 3.5e4  <class 'float'>
bool    : True or False  <class 'bool'>
complex : 3 + 4j  <class 'complex'>
list    : [1, 2, 'mohsen']  <class 'list'>
tuple   : (1, 2, 'mohsen')  <class 'tuple'>
set     :  {1, 2, 2, 3, 1, 4}  <class 'set'> and result {1, 2, 3, 4}
dict    : {'name': 'Mohsen', 'age':33}  <class 'dict'>


In [7]:
# list

my_list = list(range(10))
print(f"my_list is {my_list}")

my_list is [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
str_list = [str(value) for value in my_list]
print(f"str_list is {str_list}")
print(f"type str_list[2] = {str_list[2]} is {type(str_list[2])}")


str_list is ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
type str_list[2] = 2 is <class 'str'>


In [ ]:
# can have all type in one list
L3 = [True, 1, "mohsen", 4+5j, 12.45]
[type(item) for item in L3]

[bool, int, str, complex, float]

#### Array  in numpy 
Array is same list in python but all item have same type, Upcast   
`np.array([])`

In [21]:
import array
L = list(range(10))
A = array.array("i", L)
print(f"L is {L}\nA is {A}")
print(f"type(L) is {type(L)}\ntype(A) is {type(A)}")


L is [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
A is array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
type(L) is <class 'list'>
type(A) is <class 'array.array'>


In [39]:
import numpy as np
A = np.array([1, 2, 3])
print(f"A is {A} and type is {[type(item) for item in A]}")
A = np.array([1, 2, "a"]) # one of value is str: all value type is str
print(f"A is {A} and type is {[type(item) for item in A]}")
A = np.array([1, 2, 12.5]) # one of value is float: all value type is float
print(f"A is {A} and type is {[type(item) for item in A]}")

A is [1 2 3] and type is [<class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>]
A is ['1' '2' 'a'] and type is [<class 'numpy.str_'>, <class 'numpy.str_'>, <class 'numpy.str_'>]
A is [ 1.   2.  12.5] and type is [<class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>]


In [43]:
A = np.array([1, 2, 3])
print(f"A is {A} and type is {[type(item) for item in A]}")
# change data type
A = np.array([1, 2, 3], dtype=np.float32)
print(f"A is {A} and type is {[type(item) for item in A]}")

A is [1 2 3] and type is [<class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>]
A is [1. 2. 3.] and type is [<class 'numpy.float32'>, <class 'numpy.float32'>, <class 'numpy.float32'>]


In [48]:
# 2D array
np.array([range(i, i + 3) for i in [1, 2, 3]])

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [53]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
np.zeros((3,2), dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [58]:
np.ones((3,2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [61]:
np.ones((3,2), dtype=int) * 3.1415


array([[3.1415, 3.1415],
       [3.1415, 3.1415],
       [3.1415, 3.1415]])

In [62]:
np.full((3,2), 3.1415)

array([[3.1415, 3.1415],
       [3.1415, 3.1415],
       [3.1415, 3.1415]])

In [64]:
# 3D Array
np.full((3,2,4), 3.1415)


array([[[3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415]],

       [[3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415]],

       [[3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415]]])

In [67]:
# 4D Array
np.full((2,3,4,5), 3.1415)


array([[[[3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415, 3.1415]],

        [[3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415, 3.1415]],

        [[3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415, 3.1415]]],


       [[[3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415, 3.1415]],

        [[3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1415, 3.1415, 3.1415, 3.1415],
         [3.1415, 3.1

In [73]:
# [0 : 20) by step 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [72]:
# [0 : 10) by step 0.5
np.arange(0, 10, 0.50)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [84]:
np.random.random((3 , 4)) # (rows , columns)

array([[0.3075831 , 0.15034322, 0.96887565, 0.24546263],
       [0.70267831, 0.00318937, 0.65844923, 0.73794005],
       [0.5571798 , 0.82252962, 0.43670192, 0.84288054]])

In [89]:
np.random.normal(0, 1, (3, 3)) # (mean, std, shape)

array([[ 1.22292674,  1.02830062,  0.04509663],
       [ 0.27638405,  1.03131451,  1.47754617],
       [-0.91152804,  2.48987977,  1.72892721]])

In [95]:
np.random.randint(0, 10, (3, 2)) # [start, end) and shape(rows, columns): int

array([[0, 6],
       [8, 6],
       [8, 9]], dtype=int32)

In [103]:
np.eye(3) # 3x3 array and indetity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [108]:
np.empty(20) # show random data in RAM

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

#### Basic numpy Attributes



In [127]:
import numpy as np
np.random.seed(0) # create random in first time run and keep data

x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3, 4))
x3 = np.random.randint(10, size = (3, 4, 5))
print(x1)
print("-------------")
print(x2)
print("-------------")
print(x3)

[5 0 3 3 7 9]
-------------
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
-------------
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [136]:
print(x1)
print(f"ndim  : {x1.ndim}")
print(f"shape : {x1.shape}")
print(f"size  : {x1.size}")


[5 0 3 3 7 9]
ndim  : 1
shape : (6,)
size  : 6


In [137]:
print(x2)
print(f"ndim  : {x2.ndim}")
print(f"shape : {x2.shape}")
print(f"size  : {x2.size}")

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
ndim  : 2
shape : (3, 4)
size  : 12


In [138]:
print(x3)
print(f"ndim  : {x3.ndim}")
print(f"shape : {x3.shape}")
print(f"size  : {x3.size}")

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
ndim  : 3
shape : (3, 4, 5)
size  : 60


In [144]:
print(f"dtype: {x3.dtype} and Syntax is `x3.dtype`")

dtype: int32 and Syntax is `x3.dtype`


In [151]:
print(f"size  : {x3.size} and Syntax is `x3.size`")
print(f"itemsize: {x3.itemsize} and Syntax is `x3.itemsize`")
print(f"nbytes: {x3.nbytes} and Syntax is `x3.nbytes`")
print(f"bytes is {x3.size} x {x3.itemsize}  = {x3.size * x3.itemsize}")


size  : 60 and Syntax is `x3.size`
itemsize: 4 and Syntax is `x3.itemsize`
nbytes: 240 and Syntax is `x3.nbytes`
bytes is 60 x 4  = 240


#### Array index

In [152]:
x1

array([5, 0, 3, 3, 7, 9], dtype=int32)

In [155]:
x1[0], x1[1:5], x1[-2]

(np.int32(5), array([0, 3, 3, 7], dtype=int32), np.int32(7))

In [156]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]], dtype=int32)

In [164]:
x2[0, 1], x2[0:3, 0:3]

(np.int32(5),
 array([[3, 5, 2],
        [7, 6, 8],
        [1, 6, 7]], dtype=int32))